spring.application.name=genesis_be
spring.datasource.url=jdbc:postgresql://localhost:5432/genesis_db
spring.datasource.username=kimbeomjun
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true